version: '3'
services:
  nginx:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=chomchanok.monster
      - LETSENCRYPT_HOST=chomchanok.monster
      - LETSENCRYPT_EMAIL=chomchanok.monster
    volumes:                     
      - .:/etc/nginx/conf.d
networks:
  default:
    external: true
    name: nginx-proxy-example